Bewerage/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Bewerage.Controllers
{
    public class ContactController : Controller
    {
        public ViewResult  Index()
        {
            return View();
        }
    }
}

Bewerage/Controllers/DrinkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bewerage.Data.Interfaces;
using Bewerage.Models;
using Bewerage.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Bewerage.Controllers
{
    public class DrinkController : Controller
    {

        private readonly ICategoryRepository _categoryRepository;
        private readonly IDrinkRepository _drinkRepository;

        public DrinkController(ICategoryRepository categoryRepository, IDrinkRepository drinkRepository)
        {
            _categoryRepository = categoryRepository;
            _drinkRepository = drinkRepository;
        }
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Drink> drinks;
            string currentCategory = string.Empty;
            if (string.IsNullOrEmpty(category))
            {
                drinks = _drinkRepository.Drinks.OrderBy(n => n.DrinkId);
                currentCategory = "All drinks";
            }
            else
            {
                if(string.Equals("Alcoholic", _category, StringComparison.OrdinalIgnoreCase))
                {
                    drinks = _drinkRepository.Drinks.Where(P => P.Category.CategoryName.Equals("Alcoholic")).OrderBy(n => n.DrinkId); 
                }
                else
                    drinks = _drinkRepository.Drinks.Where(P => P.Category.CategoryName.Equals("Non-alcoholic")).OrderBy(n => n.DrinkId);

                currentCategory = category; 
            }


            var  vm = new DrinkListViewModel() {
                Drinks = drinks,
                CurrentCategory = currentCategory
            };

            return View(vm);
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Bewerage/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bewerage.Data.Interfaces;
using Bewerage.Models;
using Bewerage.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Bewerage.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IDrinkRepository _drinkREpository;
        private readonly ShoppingCart _shoppingCart; 

        public ShoppingCartController(IDrinkRepository drinkREpository, ShoppingCart shoppingCart)
        {
            _drinkREpository = drinkREpository;
            _shoppingCart = shoppingCart; 
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var scVM = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(scVM);

        }

        public RedirectToActionResult AddToShoppingCart(int drinkId)
        {
            var selectedDrink = _drinkREpository.Drinks.FirstOrDefault(d => d.DrinkId == drinkId); 
            if(selectedDrink != null)
            {
                _shoppingCart.AddToCart(selectedDrink, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int drinkId)
        {
            var selectedDrink = _drinkREpository.Drinks.FirstOrDefault(d => d.DrinkId == drinkId);
            if (selectedDrink != null)
            {
                _shoppingCart.RemoveFromCart(selectedDrink);
            }

            return RedirectToAction("Index");
        }
        
    }
}

Bewerage/Views/Shared/Carousel.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Bewerage/Views/Shared/DrinksSummery.cshtml
@model Drink

<div class="col-sm-4 col-lg-4 col-lg-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Drink" asp-action="Details" asp-route-id="@Model.DrinkId"> @Model.Name</a>
            </h3>
            <p> Price : @Model.ShortDescription</p>
        </div>

        <div class="addToCart text-right">
            <p class="button">
                <a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" 
                                                           asp-action="AddToShoppingCart" asp-route-drinkId="@Model.DrinkId">
                    Add to Cart
                </a>
            </p>
        </div>
    </div>
</div>

Bewerage/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log Off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li> <a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login" >Log in</a></li>
    </ul>
}

Bewerage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapse" data-toggle="colapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only"> Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ui class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index"> Home</a> </li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="Index"> Contact us</a> </li>
                    @await Component.InvokeAsync("ShoppingCartSummary")

                </ui>
                @await Html.PartialAsync("LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <a target="_blank" href="https://github.com/gbeydtha"> &copy; 2020 - git beydtha</a>
        </footer>
    </div>
</body>
</html>